### PR TITLE
bug fix: creating subsequent games from mobile

### LINKED ISSUE #483: fix bug in creation of subsequent games
https://dosomething.mcommons.com/profiles/178995605
https://dosomething.mcommons.com/profiles/178995939
https://dosomething.mcommons.com/profiles/178996041

### PR DESCRIPTION
**Pull request by tongxiang**
#### What's this PR do?
This PR adds a bug fix. (See details of the bug below.) We fix this by: 

1. Adding a timestamp to game create config documents, and querying only for the most recent document. 
2. Creating [a new MData](https://dosomething.mcommons.com/mdatas/12211) with a new query param, `alpha_first_name_query_response`, to the mdata attached to [the first message of the mobile create flow](https://dosomething.mcommons.com/campaigns/135439/opt_in_paths/181501), as well as the ["invalid alpha first name"](https://dosomething.mcommons.com/campaigns/135439/opt_in_paths/181645) message.  
3. Checking for the presence of this query param within `SGCreateFromMobileController.prototype.processRequest` in order to determine whether or not a new game create config doc should be created. If it's present, then the user has just texted in their first name to the first message in the mobile create flow, and we create a new document. 
4. General refactoring and modification of tests. 

#### Where should the reviewer start?
`SGCreateFromMobileController.js`. 

#### How should this be manually tested?
Using Postman, begin the game creation mobile flow. Begin another game creation mobile flow with the same user phone number. Make sure that you can finish the second flow without interfering with the first flow. 

You can use [this postman collection](https://www.getpostman.com/collections/128ccf5f25ffd622572d) to test. 

#### Any background context you want to provide?
Previously, when a user creates a game from mobile, is brought into another flow, and then begins to create another game from mobile, the flow of messages returned is off. 

This is because the first game-create-config doc created when the user first creates a game from mobile is never deleted. When the user texts back again, that same doc is found and updated by the user's responses. This creates problems. 

Let me give you an example: 

User texts in `Tong` to create the first game from mobile, creating the following game config doc: 

```
{ _id: 55ca758920ddda069cb3534c,
  alpha_mobile: '15555550479',
  story_id: 400,
  story_type: 'competitive-story',
  alpha_first_name: 'Tong',
  __v: 0,
  beta_mobile_0: null,
  beta_mobile_1: null,
  beta_mobile_2: null,
  beta_first_name_0: '',
  beta_first_name_1: '',
  beta_first_name_2: '',
  created_at: Tue Aug 11 2015 18:22:01 GMT-0400 (EDT) }
```
When the user texts back in attempting to create a second mobile flow, the previous game create config doc is discovered because the query in `SGCreateFromMobileController.js` - `.processRequest()` previously searched for any documents with that user's phone number. 

So when that user texts back in with `Tong`, attempting to create another first game from mobile, our flow in `SGCreateFromMobileController` queries for the user doc belonging to Tong's number, and the flow discovers that the `alpha_first_name` param is already occupied. It attempts to place the new `Tong` input as being meant for `beta_mobile_0`, but since `Tong` doesn't include a number, the control flow sends an error message that the alpha has not properly texted back a valid beta name and number. 

#### What are the relevant tickets?
Closes #483.

### CODE REVIEW

File: app/lib/sms-games/controllers/SGCreateFromMobileController.js [hunk 1]
```diff
@@ -65,110 +64,105 @@ SGCreateFromMobileController.prototype.processRequest = function(request, respon
...
+      alpha_mobile: request.body.phone,
+      story_id: request.query.story_id,
+      story_type: request.query.story_type,
+      game_type: (request.query.game_type || '')
+    };
+    var message = request.body.args;
+    // User should have responded with the alpha name. If so, create game create config doc.
+    if (smsHelper.hasLetters(message)) {
+      doc.alpha_first_name = smsHelper.getLetters(message);
+      var createGameConfig = configModel.create(doc);
```
Comment (jonuy) [inline app/lib/sms-games/controllers/SGCreateFromMobileController.js]: Potential `TODO` here is to also delete any existing create-game docs for this user number and game id.

File: app/lib/sms-games/controllers/SGCreateFromMobileController.js [hunk 2]
```diff
@@ -55,7 +55,6 @@ SGCreateFromMobileController.prototype.processRequest = function(request, respon
   }
 
   self = this;
-  self.createGame = createGame;
   request = request;
```
Comment (jonuy) [inline app/lib/sms-games/controllers/SGCreateFromMobileController.js]:
```
request = request;
responses = response;
```

This is curious. Any idea why we might've done this before?

File: app/lib/sms-games/controllers/SGCreateFromMobileController.js [hunk 3]
```diff
@@ -253,6 +247,7 @@ function ErrorAbortPromiseChain() {
  */
 SGCreateFromMobileController.prototype._updateDocument = function(configDoc) {
   var editedDoc = {
+      _id: configDoc._id,
```
Comment (jonuy) [inline app/lib/sms-games/controllers/SGCreateFromMobileController.js]: I think this right here is our problem with the failing tests.

**Comment by jonuy** [comment]
As we talked about, I think it's fine to merge this in since it's a test that's been failing for about 3 weeks now. Just make sure to then follow up the merge and deploy with:

- testing game creation on production
- creating an issue in this repo with a copy of the error message the tests are throwing and links to a couple of the wercker tests that failed

File: app/lib/sms-games/controllers/SGCreateFromMobileController.js (hunk 2 above)
Comment (tongxiang) [inline app/lib/sms-games/controllers/SGCreateFromMobileController.js]: Not sure, unfortunately.

Comment (tongxiang) [inline app/lib/sms-games/controllers/SGCreateFromMobileController.js]: Perhaps to access the request in the callback? Still seems to be working if we take this out, though.
