### PR TITLE
Removes hardcoded DonorsChoose olderThan param

### LINKED ISSUE #520: Science Sleuth error response
Currently texting in REWARD results in a "Oof! something went wrong" because the opt-in paths are looking for custom fields which no longer exist. 

This isn't an issue we necessarily need to make any code changes for, this can be closed out once we add the Custom Fields we need into Mobile Commons and verify things work.

From [`DonationController.js`](https://github.com/DoSomething/ds-mdata-responder/blob/2a837e05bb995c098d1c3097ff9ec55e5ff9bbda/app/lib/donations/controllers/DonorsChooseDonationController.js#L171):
````
        var mobileCommonsCustomFields = {
          SS_fulfillment_trailer:   entities.decode(selectedProposal.fulfillmentTrailer), 
          SS_teacher_name :         entities.decode(selectedProposal.teacherName), 
          SS_school_name :          entities.decode(selectedProposal.schoolName),
          SS_proj_location:         location
        };
````

cc @deadlybutter @jamjensen @classicfreddie 

custom_fields

### PR DESCRIPTION
**Pull request by aaronschachter**
#### What's this PR do?
* Removes a hardcoded `olderThan=1445299201000` (Tue, 20 Oct 2015 00:00:01 GMT) query string param to get results back from the DonorsChoose API. Fixes #520, refs https://github.com/DoSomething/ds-mdata-responder/issues/539#issuecomment-236728667
* Adds `debug` logging to `DonorsChooseDonationController` and `mobilecommons.profile_update`

#### How should this be reviewed?
Run locally and POST to `http://localhost:5000/donations/donors-choose/start?id=201` with your phone number. You should receive a "Awesome we want [teacher name].." message back, instead of the "Oof! Something went wrong message".

Can additionally inspect queries in browser:
* [New request URL](http://api.donorschoose.org/common/json_feed.html?&subject4=-4&sortBy=2&costToCompleteRange=10+TO+10000&max=1&APIKey=DONORSCHOOSE)
* [Initial request URL (with olderThan)](http://api.donorschoose.org/common/json_feed.html?&subject4=-4&sortBy=2&costToCompleteRange=10+TO+10000&max=1&APIKey=DONORSCHOOSE&olderThan=1445299201000)

#### Any background context you want to provide?
I've been testing with configs `donorschoose` document id=201 for now, but we'll want to use id=301 once it has updated OIPs (refs #539)

cc @mshmsh5000

### CODE REVIEW

File: app/lib/donations/controllers/DonorsChooseDonationController.js [hunk 1]
```diff
@@ -119,29 +116,24 @@ DonorsChooseDonationController.prototype.start = function(request, response) {
...
-  var costToCompleteRange = 'costToCompleteRange=' + DONATION_AMOUNT + '+TO+' + COST_TO_COMPLETE_UPPER_LIMIT; 
-  var projectsCreatedBy = 'olderThan=' + PROJECT_CREATION_CUTOFF_DATE;
-  // Maximum number of results to return. 
-  var maxNumberOfResults = '1';
-  var filterParams = subjectFilter + '&' + urgencySort + '&' + costToCompleteRange + '&' + projectsCreatedBy + '&';
-  var requestUrlString = donorsChooseProposalsQueryBaseURL + filterParams + 'APIKey=' + donorsChooseApiKey + '&max=' + maxNumberOfResults;
+DonorsChooseDonationController.prototype.findProject = function(mobileNumber, config) {
+  var requestUrlString = donorsChooseProposalsQueryBaseURL;
+  requestUrlString += '&subject4=-4'; 
+  requestUrlString += '&sortBy=2';
```
Comment (aaronschachter) [inline app/lib/donations/controllers/DonorsChooseDonationController.js]: Intentional change here to `sortBy=2`
> Cost shows projects with the lowest cost to complete at the top

From previous requests for `sortBy=0:`
> Urgency shows projects with higher urgency at the top

Refs https://data.donorschoose.org/docs/project-listing/json-requests/
